// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfg4NLYKGo1ilFDsoS2bd3sUR0oyYVPSk',
    appId: '1:90879601036:web:008eae57664a8dc2e78ea9',
    messagingSenderId: '90879601036',
    projectId: 'adidas-ecommerce-45986',
    authDomain: 'adidas-ecommerce-45986.firebaseapp.com',
    storageBucket: 'adidas-ecommerce-45986.appspot.com',
    measurementId: 'G-1F9F35T3Q6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3r_6x3K5YeD9_DmW2BbVc8GCLewddSB8',
    appId: '1:90879601036:android:18836a2d78e44072e78ea9',
    messagingSenderId: '90879601036',
    projectId: 'adidas-ecommerce-45986',
    storageBucket: 'adidas-ecommerce-45986.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIUFfd2f0ITVbF_EwOgl7stdHSw54TmdM',
    appId: '1:90879601036:ios:12ce6bb0347d4181e78ea9',
    messagingSenderId: '90879601036',
    projectId: 'adidas-ecommerce-45986',
    storageBucket: 'adidas-ecommerce-45986.appspot.com',
    iosBundleId: 'lk.apple',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIUFfd2f0ITVbF_EwOgl7stdHSw54TmdM',
    appId: '1:90879601036:ios:fc61447785860068e78ea9',
    messagingSenderId: '90879601036',
    projectId: 'adidas-ecommerce-45986',
    storageBucket: 'adidas-ecommerce-45986.appspot.com',
    iosBundleId: 'com.example.ecommerceAddidas',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAfg4NLYKGo1ilFDsoS2bd3sUR0oyYVPSk',
    appId: '1:90879601036:web:e8fe2215f9e848f4e78ea9',
    messagingSenderId: '90879601036',
    projectId: 'adidas-ecommerce-45986',
    authDomain: 'adidas-ecommerce-45986.firebaseapp.com',
    storageBucket: 'adidas-ecommerce-45986.appspot.com',
    measurementId: 'G-68QDSF0BM2',
  );
}
